module.exports = {
  projects: [
    '<rootDir>/apps/wow',
    '<rootDir>/apps/api',
    '<rootDir>/libs/user',
    '<rootDir>/libs/prisma',
    '<rootDir>/libs/auth',
    '<rootDir>/libs/order',
    '<rootDir>/libs/partner',
    '<rootDir>/libs/pick',
    '<rootDir>/libs/pick-boy',
    '<rootDir>/libs/delivery-boy',
    '<rootDir>/libs/delivery',
    '<rootDir>/libs/dto',
    '<rootDir>/libs/guards',
    '<rootDir>/libs/payment',
    '<rootDir>/libs/supplier',
    '<rootDir>/libs/zone',
    '<rootDir>/libs/config',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/auth-ui',
    '<rootDir>/libs/file-handler',
    '<rootDir>/libs/tasks',
  ],
};
