module.exports = {
  projects: [
    '<rootDir>/apps/wow',
    '<rootDir>/apps/api',
    '<rootDir>/libs/nest/user',
    '<rootDir>/libs/nest/prisma',
    '<rootDir>/libs/nest/auth',
    '<rootDir>/libs/nest/order',
    '<rootDir>/libs/nest/partner',
    '<rootDir>/libs/nest/pick',
    '<rootDir>/libs/nest/pick-boy',
    '<rootDir>/libs/nest/delivery-boy',
    '<rootDir>/libs/nest/delivery',
    '<rootDir>/libs/nest/dto',
    '<rootDir>/libs/guards',
    '<rootDir>/libs/nest/payment',
    '<rootDir>/libs/nest/supplier',
    '<rootDir>/libs/nest/region',
    '<rootDir>/libs/config',
    '<rootDir>/libs/nest/auth-ui',
    '<rootDir>/libs/file-handler',
    '<rootDir>/libs/nest/task',
    '<rootDir>/libs/ui/lib/user',
    '<rootDir>/libs/ui/src/lib/user',
    '<rootDir>/libs/auth',
  ],
};
